[package]
name = "toy_rust_db"
version = "0.1.0"
authors = ["Lily <rctcwyvrn@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "toy_rust_db"
path = "src/lib.rs"

[dependencies]
csv = "*"